let encuentros = {
    title: "Encuentros",
    subtitle: "An augmented documentary about home and personal borders",
    date: "Nov. 2020",
    credits: "Directed/Written/Produced by Patricia Mascarell & Daniel Vera",
    imagesPath: "./projects/assets/encuentros",
    description: "When thinking about home, rather often the first image that comes to mind is a physical space. However, even though that first thought is probably based on the need of a context, the thoughts quickly turn into memories that go beyond the strict materiality of the house. That is, really, where the combination of house and identity turn into what we usually define as home. Home is the virtual house, the time-based abstract layer generated by the inhabitant as a response to the urgency of translating their own identity into space.",
    links: ["https://encuentrosdocumentaries.com/"],
    video: "https://vimeo.com/530390220",
    tags: ["Photogrammetry", "Augmented Documentary"],
    type: "Digital Architecture",
    logo: "",
};

let projectData = [encuentros];

export default projectData;